// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proyecto_FInal_Grupo_1.Data;

#nullable disable

namespace Proyecto_FInal_Grupo_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_FInal_Grupo_1.Models.CarSponsor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamCarId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.HasIndex("TeamCarId");

                    b.ToTable("CarSponsors");
                });

            modelBuilder.Entity("Proyecto_FInal_Grupo_1.Models.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SponsorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamCarId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.HasIndex("TeamCarId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Proyecto_FInal_Grupo_1.Models.Sponsor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("Proyecto_FInal_Grupo_1.Models.TeamCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TeamCars");
                });

            modelBuilder.Entity("Proyecto_FInal_Grupo_1.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentJwtId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RefreshTokenRevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Proyecto_FInal_Grupo_1.Models.CarSponsor", b =>
                {
                    b.HasOne("Proyecto_FInal_Grupo_1.Models.Sponsor", "Sponsor")
                        .WithMany("CarSponsors")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_FInal_Grupo_1.Models.TeamCar", "TeamCar")
                        .WithMany("CarSponsors")
                        .HasForeignKey("TeamCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sponsor");

                    b.Navigation("TeamCar");
                });

            modelBuilder.Entity("Proyecto_FInal_Grupo_1.Models.Driver", b =>
                {
                    b.HasOne("Proyecto_FInal_Grupo_1.Models.Sponsor", "Sponsor")
                        .WithMany("Drivers")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_FInal_Grupo_1.Models.TeamCar", "TeamCar")
                        .WithOne("Driver")
                        .HasForeignKey("Proyecto_FInal_Grupo_1.Models.Driver", "TeamCarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sponsor");

                    b.Navigation("TeamCar");
                });

            modelBuilder.Entity("Proyecto_FInal_Grupo_1.Models.Sponsor", b =>
                {
                    b.Navigation("CarSponsors");

                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("Proyecto_FInal_Grupo_1.Models.TeamCar", b =>
                {
                    b.Navigation("CarSponsors");

                    b.Navigation("Driver");
                });
#pragma warning restore 612, 618
        }
    }
}
